[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
    NPM_FLAGS = "--version"